import { Activity, Clock3, Gauge, RadioTower } from "lucide-react";
import { ApiUnavailable } from "@/components/api-unavailable";
import { DeviceActions } from "@/components/device-actions";
import { PageHeader } from "@/components/page-header";
import { StatusChip } from "@/components/status-chip";
import { api, ApiUnavailableError } from "@/lib/api";

export default async function DevicesPage() {
  try {
    const devices = await api.devices();
    return <><PageHeader title="Imaging Device Fleet" description="Live telemetry persisted from the separate C++20 device-engine simulation over TCP JSON-line IPC."/><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{devices.map((device) => <article key={device.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-cyan-50 p-2 text-cyan-800"><RadioTower size={20}/></div><div><h2 className="font-semibold text-slate-950">{device.device_identifier}</h2><p className="text-sm text-slate-600">{device.name}</p></div></div><StatusChip value={device.status}/></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs uppercase tracking-wide text-slate-500">Modality</dt><dd className="mt-1 font-semibold">{device.modality}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-500">Location</dt><dd className="mt-1 font-semibold">{device.location || "—"}</dd></div><div><dt className="flex items-center gap-1 text-xs uppercase tracking-wide text-slate-500"><Gauge size={13}/> Utilization</dt><dd className="mt-1 font-semibold">{device.utilization}%</dd></div><div><dt className="flex items-center gap-1 text-xs uppercase tracking-wide text-slate-500"><Activity size={13}/> Queue</dt><dd className="mt-1 font-semibold">{device.queue_depth}</dd></div></dl><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-700" style={{ width: `${device.utilization}%` }}/></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13}/>{device.last_heartbeat ? new Date(device.last_heartbeat).toLocaleTimeString() : "No heartbeat"}</span><DeviceActions deviceId={device.device_identifier} faulted={device.status === "FAULT"}/></div></article>)}{devices.length === 0 && <div className="col-span-full rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No device telemetry yet. The C++ engine may still be connecting.</div>}</div></>;
  } catch (error) { return <><PageHeader title="Imaging Device Fleet" description="C++ device telemetry."/><ApiUnavailable detail={error instanceof ApiUnavailableError ? error.message : undefined}/></>; }
}
