import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { ApiUnavailable } from "@/components/api-unavailable";
import { PageHeader } from "@/components/page-header";
import { StatusChip } from "@/components/status-chip";
import { api, ApiUnavailableError } from "@/lib/api";

export default async function StudyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  try {
    const study = await api.study(id);
    return (
      <>
        <PageHeader title={study.study_description || "Study details"} description={`${study.patient.patient_identifier} · ${study.patient.display_name}`} action={study.viewer_url ? <a href={study.viewer_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-cyan-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-900">Open DICOM Viewer <ExternalLink size={16} /></a> : undefined} />
        <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
          <section className="rounded-xl border border-slate-200 bg-white p-6">
            <h2 className="font-semibold text-slate-950">Study information</h2>
            <dl className="mt-5 grid gap-x-8 gap-y-5 sm:grid-cols-2">
              {[
                ["Modality", study.modality || "—"],
                ["Body part", study.body_part_examined || "—"],
                ["Study date", study.study_date || "—"],
                ["Manufacturer", study.manufacturer || "—"],
                ["Institution", study.institution_name || "—"],
                ["Series / Images", `${study.series_count} / ${study.instance_count}`],
              ].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-900">{value}</dd></div>)}
            </dl>
            <div className="mt-6 rounded-lg bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">StudyInstanceUID</div><div className="mt-2 break-all font-mono text-xs text-slate-700">{study.study_instance_uid}</div></div>
          </section>

          <section className="rounded-xl border border-slate-200 bg-white p-6">
            <h2 className="font-semibold text-slate-950">Operational state</h2>
            <div className="mt-5 flex flex-wrap gap-3"><StatusChip value={study.status} /><StatusChip value={study.validation_status} /></div>
            <div className="mt-6 space-y-3 text-sm"><p className="text-slate-600">Quality and metadata are generated by the backend from actual ingestion events.</p><div className="flex flex-wrap gap-2"><Link href={`/studies/${id}/metadata`} className="rounded-lg border border-slate-300 px-3 py-2 font-semibold text-slate-700 hover:bg-slate-50">View metadata</Link><Link href={`/studies/${id}/quality`} className="rounded-lg border border-slate-300 px-3 py-2 font-semibold text-slate-700 hover:bg-slate-50">View Quality Gate</Link></div></div>
          </section>
        </div>

        <section className="mt-5 rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="font-semibold text-slate-950">Series</h2>
          <div className="mt-4 divide-y divide-slate-100 border-y border-slate-100">
            {study.series.map((series) => <div key={series.id} className="grid gap-3 py-4 sm:grid-cols-[80px_1fr_120px]"><div className="text-sm font-semibold text-slate-700">#{series.series_number ?? "—"}</div><div><div className="text-sm font-medium text-slate-900">{series.description || "Unnamed series"}</div><div className="mt-1 break-all font-mono text-[11px] text-slate-500">{series.series_instance_uid}</div></div><div className="text-sm text-slate-600">{series.instance_count} images</div></div>)}
            {study.series.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">No series records.</p> : null}
          </div>
        </section>
      </>
    );
  } catch (error) {
    return <><PageHeader title="Study details" description="Live study information from Axiom." /><ApiUnavailable detail={error instanceof ApiUnavailableError ? error.message : undefined} /></>;
  }
}
